routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'Forms', 'prefix' => 'forms'], function () {
    Route::resource('send-events-file', 'SendEventsFileController')->only([
        'store', 'create'
    ]);
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Forms/SendEventsFileController.php
<?php

namespace App\Http\Controllers\Forms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SendEventsFileController extends Controller
{
    public function create()
    {
        return view('send-events-file.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'file' => 'required|mimes:txt|max:2048',
        ]);

        $fileName = 'eventos.'.$request->file->extension();

        $request->file->move(public_path('uploads'), $fileName);

        return back()
            ->with('success','Arquivo enviado com sucesso.')
            ->with('file', $fileName);
    }
}

app/Http/Controllers/Meetings/Meetups.php
<?php


namespace App\Http\Controllers\Meetings;


use Illuminate\Http\JsonResponse;

interface Meetups
{
    public function showList(): JsonResponse ;
}

app/Http/Controllers/Meetings/MeetupsBase.php
<?php


namespace App\Http\Controllers\Meetings;


use Carbon\Carbon;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;

abstract class MeetupsBase
{
    public $startFirstPeriod;
    public $hourLunch;
    public $startSecondPeriod;
    public $happyHour;

    public function duration(string $value, string $textToTime = null, string $timeToReplaceText = null): string
    {
        $resultMatch = $this->getMatchTimeInString($value);
        return strpos($value, $textToTime) ? $timeToReplaceText : $this->getTimeExtractedToString($resultMatch);
    }

    public function horary(string $start, string $interval): string
    {
        return Carbon::createFromFormat('H:i', $start)
            ->addMinutes(intval($interval))->format('H:i');
    }

    public function title(string $text): string
    {
        return $text;
    }

    public function removeProcessedPeriod(Collection $collection, array $removedItems): array
    {
        $restItemsToProcess = $collection->filter(function ($value, $key) use ($removedItems) {

            $removedKey = collect($removedItems)->filter(function ($val) use ($key) {
                return $val === $key;
            })->toArray();

            return $key !== Arr::first($removedKey) ? $value : null;
        })->toArray();

        return array_values($restItemsToProcess);
    }

    protected function getTimeExtractedToString(array $array): string
    {
        return Arr::last($array);
    }

    protected function getMatchTimeInString(string $string): array
    {
        preg_match("/([0-9]+)min/", $string, $matches);
        return $matches;
    }
}

app/Http/Controllers/Meetings/Talks.php
<?php


namespace App\Http\Controllers\Meetings;


use Illuminate\Http\JsonResponse;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\File;

class Talks extends MeetupsBase implements Meetups
{
    private $data;
    public $startFirstPeriod = "09:00";
    public $hourLunch = "12:00 Hour Lunch";
    public $startSecondPeriod = "01:00";
    public $happyHour = "05:00 Happy Hour";
    private $processedPeriod;
    private $restProcessedPeriod;

    public function __construct()
    {
        $this->processedPeriod = [];
        $this->restProcessedPeriod = null;
    }

    public function showList(): JsonResponse
    {
        return response()->json($this->createListTalks(), 200);
    }

    private function createListTalks(): array
    {
        $collection = $this->getTitleAndDurationOfTalk();

        $count = 1;
        while (empty($this->processedPeriod) || !empty($this->restProcessedPeriod)) {
            $results = empty($this->restProcessedPeriod) ?
                $this->processAllPeriods($collection) : $this->processAllPeriods(collect($this->restProcessedPeriod));

            $this->processedPeriod[] = [
                'title' => "Track $count",
                'data' => Arr::first($results)
            ];
            $this->restProcessedPeriod = Arr::last($results);
            $count++;
        }

        return [
            'data' => $this->processedPeriod
        ];
    }

    private function getTitleAndDurationOfTalk(): Collection
    {
        return collect($this->getDataFile())->map(function ($values) {
            return [
                'title' => $this->title($values),
                'duration' => $this->duration($values, 'lightning', '5'),
            ];
        });
    }

    private function processAllPeriods(Collection $collection)
    {
        $firstPeriod = $this->processedPeriodAndGetRestItems($collection, [], $this->startFirstPeriod, $this->hourLunch, 180, []);
        $restProcessedPeriod = $this->removeProcessedPeriod($collection, Arr::last($firstPeriod));

        $secondPeriod = $this->processedPeriodAndGetRestItems(collect($restProcessedPeriod), [], $this->startSecondPeriod, $this->happyHour, 240, []);
        $restProcessedPeriod = $this->removeProcessedPeriod(collect($restProcessedPeriod), Arr::last($secondPeriod));

        return [
            array_filter(
                array_merge(Arr::first($firstPeriod), Arr::first($secondPeriod))
            ),
            $restProcessedPeriod
        ];
    }

    private function processedPeriodAndGetRestItems(Collection $collection, array $durationPeriod, string $startTalk,
                                   string $endPeriod, int $limitPeriodInMinutes, array $removedItems)
    {
        $period = $collection->map(function ($valueItem, $key) use (
            &$durationPeriod, &$startTalk, $limitPeriodInMinutes, $endPeriod, &$removedItems
        ) {
            $totalMinutes = $valueItem['duration'] + array_sum($durationPeriod);
            if ($totalMinutes > $limitPeriodInMinutes) {
                return null;
            }

            $durationPeriod[] = $valueItem['duration'];
            $removedItems[] = $key;
            $fullTitle = $startTalk . ' ' . $valueItem['title'];
            $startTalk = $this->horary($startTalk, $valueItem['duration']);

            return $fullTitle;

        })->toArray();

        $period[] = !empty($period) ? $endPeriod : null;

        return [
            array_filter($period),
            $removedItems
        ];
    }

    private function getDataFile(): array
    {
        $filename = public_path('uploads') . '/eventos.txt';
        if(!File::exists($filename)) {
            return [];
        }

        $file = File::get($filename);
        return array_filter(array_map('trim', explode(',', $file)));
    }
}

resources/views/send-events-file/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
<div class="flex-center position-ref full-height">
    <div class="content">
        <div class="title m-b-md">
            @if ($message = Session::get('success'))
                <p>{{ $message }}</p>
            @endif

            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('send-events-file.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">

                    <div>
                        <input type="file" name="file" class="form-control">
                    </div>

                    <div>
                        <button type="submit" class="btn btn-success">Enviar Arquivo</button>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>